### ISSUE TITLE
关于运行时最上面一直在的状态栏

### ISSUE THREAD

**Issue by xuwhao** [boyan01/flutter-tetris#10]
你好！很喜欢你这款游戏。目前也正在学习。只是游戏最上面那一条系统状态栏横着让强迫症很难受。这个可以消除吗？

**Comment by boyan01** [comment]
可以消除的。把页面设置为全屏的就行，API 参见
https://api.flutter.dev/flutter/services/SystemChrome-class.html

**Comment by xuwhao** [comment]
thanks！
