### ISSUE TITLE
The windows navigation key not response.

### ISSUE THREAD

**Issue by liudonghua123** [boyan01/flutter-tetris#12]
I tried the windows version of this game, the navigation key not works. I debugged the code and find the key issue is related to keyboard key matches, I use logicalKey  instead of physicalKey.

Another problem is the donation button did not unfocus when press-release. so I manully unfocus it. and the vendor files like `android`/`ios`/`web`/`macos`/`linux`/`windows` were too old, so I updated them too.

see more details on https://github.com/boyan01/flutter-tetris/pull/11.

**Comment by boyan01** [comment]
close by #11
