### ISSUE TITLE
有打算迁移到空安全吗？

### ISSUE THREAD

**Issue by gionlime** [boyan01/flutter-tetris#14]
有打算迁移到空安全吗？

**Comment by boyan01** [comment]
Wheref Team 在 9 月份的时候给我发过邮件，说是能将项目升级迁移到  flutter 2.0 null safety。 

所以我在等他们发 PR 呢~~

**Comment by yaoyao2mm** [comment]
> Wheref Team 在 9 月份的时候给我发过邮件，说是能将项目升级迁移到 flutter 2.0 null safety。
> 
> 所以我在等他们发 PR 呢~~

期待😘

**Comment by gionlime** [comment]
> Wheref Team 在 9 月份的时候给我发过邮件，说是能将项目升级迁移到 flutter 2.0 null safety。
> 
> 所以我在等他们发 PR 呢~~

期待

**Comment by Tepehan** [comment]
hi,there ı have some issue with part of code in tetris app.I have changed List.filled(shape[0].length, null, growable: false); to List.filled(shape[0].length, [], growable: false); as below.Then  ı got another error as IndexError (RangeError (index): Index out of range: no indices are valid: 0)  in this line (   result[col][row] = shape[shape.length - 1 - row][col];    ) 
Could you help me ?Thanks in advance!!!

 Block rotate() {
    // List.filled(shape[0].length, null, growable: false);
    List<List<int>> result = List.filled(shape[0].length, [], growable: false);
    for (int row = 0; row < shape.length; row++) {
      for (int col = 0; col < shape[row].length; col++) {
        if (result[col] == null) {
          result[col] = List.filled(shape.length, 0, growable: false);
        }
        result[col][row] = shape[shape.length - 1 - row][col];
      }
    }

**Comment by Tepehan** [comment]
Hey there again.I solved it . I publish the newest code . Anyone who may encountered with the same issue.
Block rotate() {
    // List.filled(shape[0].length, null, growable: false);
    int shapeRow = shape[0].length;
    List<List<int>> result = List.filled(shapeRow, [], growable: false);
    for (int row = 0; row < shape.length; row++) {
      for (int col = 0; col < shape[row].length; col++) {
        if (result[col].isEmpty) {
          result[col] = List.filled(shape.length, 0, growable: false);
        }
        result[col][row] = shape[shape.length - 1 - row][col];
      }
    }
