### ISSUE TITLE
mac build error

### ISSUE THREAD

**Issue by yehot** [boyan01/flutter-tetris#5]
➜  flutter-tetris git:(master) ✗ flutter run          
Launching lib/main.dart on iPhone XR in debug mode...
Running pod install...                                              1.1s
CocoaPods' output:

      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Pods/.symlinks/flutter/ios`
    -> Fetching podspec for `soundpool` from `Pods/.symlinks/plugins/soundpool/ios`

    Resolving dependencies of `Podfile`

    Comparing resolved specification to the sandbox manifest
      A Flutter
      A soundpool

    Downloading dependencies

    -> Installing Flutter (1.0.0)

    -> Installing soundpool (0.0.1)
      - Running pre install hooks
        - Podfile
    [!] Unable to determine Swift version for the following pods:

    - `soundpool` does not specify a Swift version and none of the targets (`Runner`)
    integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the
    `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

    /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.0/lib/cocoapods/installer/xcode/target_va
    lidator.rb:115:in `verify_swift_pods_swift_version'
    /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.0/lib/cocoapods/installer/xcode/target_va
    lidator.rb:37:in `validate!'
    /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:459:in
    `validate_targets'
    /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:138:in
    `install!'
    /usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.0/lib/cocoapods/command/install.rb:48:in
    `run'
    /usr/local/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  

pod version: 1.6.0

**Comment by kuroky** [comment]
iOS上没有这个库 'soundpool'

**Comment by boyan01** [comment]
上次出现过这个问题,然后在这一版 c3291ebfc61cc7db4cc6f973b82ff66759eb6846 修复了.

在昨晚的一次提交里面升级了soundpool这个库,没想到又重现了.

现在身边也没有Mac,不太方便修改. 要不大兄弟你有时间改改然后pr过来呗.

**Comment by boyan01** [comment]
@yehot my pod version 1.5.3 works fine.

I don't have iOS development experience. so maybe you can try to switch your pop version to 1.5.3
