### ISSUE TITLE
音频没有声音

### ISSUE THREAD

**Issue by yah0130** [boyan01/flutter-tetris#6]
我clone下来后运行，声音没有

**Comment by boyan01** [comment]
是 Android 还是 iOS？

**Comment by yah0130** [comment]
> 是 Android 还是 iOS？
不好意思是我自己的问题，尴尬

**Comment by boyan01** [comment]
没事哈，那我就Close了。

**Comment by simonfire007** [comment]
@boyan01 ubuntu编译运行没有声音，还有初始窗口能不能设置一下，现在的情况是左右拉伸，然后看不到下面的按钮了。还有怎么如果能绑定键盘按键就好了。
编译后，主程序文件只有100多k，然后一个so库文件90多m，资源文件30多m，运行占内存100多m。桌面版的路还很长呀。

**Comment by boyan01** [comment]
> @boyan01 ubuntu编译运行没有声音，

Flutter没有提供声音相关的api，于是使用了第三方的类库。目前这个类库只支持Android、iOS的，所以在其他平台就没声音了。

> 还有初始窗口能不能设置一下，现在的情况是左右拉伸，然后看不到下面的按钮了。

目前这确实是个问题，没有对宽高比做一个限制。有时间我再加一下相关的逻辑吧~

> 还有怎么如果能绑定键盘按键就好了。

目前是绑定按键逻辑的。但是不知道为什么在Windows平台上，按键Event和SDK定义不太一致，估计Linux也有类似的问题吧。

> 编译后，主程序文件只有100多k，然后一个so库文件90多m，资源文件30多m，运行占内存100多m。桌面版的路还很长呀。

哈哈，是啊，目前Flutter的目标也就是能在桌面端“run”起来吧。要等进入可用阶段，感觉要等不短时间。
