### ISSUE TITLE
error: Undefined name 'PhysicalKeyboardKey'

### ISSUE THREAD

**Issue by htyxz8802** [boyan01/flutter-tetris#7]
error: Undefined name 'PhysicalKeyboardKey'. (undefined_identifier at [tetris] lib\gamer\keyboard.dart:43)

**Comment by boyan01** [comment]
what's your flutter version?

**Comment by htyxz8802** [comment]
fultter v1.0.0

**Comment by boyan01** [comment]
need upgrade to latest stable version v1.5.4-hotfix.2

https://flutter.dev/docs/development/tools/sdk/releases

**Comment by htyxz8802** [comment]
thanks, I will upgrade!
