### ISSUE TITLE
windows/macos/linux平台怎么编译？

### ISSUE THREAD

**Issue by zinwalin** [boyan01/flutter-tetris#8]
感谢。

**Comment by boyan01** [comment]
以 macos 为例：
1. 需要切换 flutter 分支到 dev/master，添加环境变量 ENABLE_FLUTTER_DESKTOP=true
```bash
export ENABLE_FLUTTER_DESKTOP=true
```
执行完这一步之后，使用 flutter devices 命令，可以看到已连接的设备中包含macOS

![image](https://user-images.githubusercontent.com/17426470/60939723-5191fb00-a30b-11e9-8afb-e6c49498d704.png)

2. 运行
```bash
flutter run -d macOS
```
3. 如果上一步有错的话，将 https://github.com/google/flutter-desktop-embedding 仓库 example 中对应的平台构建文件夹复制到本项目并覆盖原有文件。
即拷贝 flutter-desktop-embedding/example/macos 到 flutter-tetris/macos
**若此步骤无用，可以尝试直接运行/编译flutter-desktop-embedding/example，如果失败，提交 issue 给 google 即可**

4. 编译成品。如果失败，也尝试一下第3步。
```
flutter build macos
```

**Comment by GanZhiXiong** [comment]
那怎么编译windows App呢？
使用flutter build windows 吗？

![image](https://user-images.githubusercontent.com/27394631/63680041-4cd6c700-c825-11e9-8963-1276b2485dc3.png)
我再macOS系统使用flutter build windows有问题啊？

**Comment by boyan01** [comment]
只能在 windows 平台上编译 windows app

**Comment by GanZhiXiong** [comment]
编译linux可执行文件也是一样必须要在linux上吗？
那还得每个平台安装flutter环境进行build，这样太麻烦了哈！

**Comment by boyan01** [comment]
没办法，平台限制。可以用虚拟机，或者用持续集成工具进行编译。

**Comment by GanZhiXiong** [comment]
大佬，是用虚拟机，还是持续集成工具编译的呢？😀

**Comment by boyan01** [comment]
都行，觉得哪个方便就用哪个呗。
